services:
  db:
    image: postgres:17
    container_name: admission_db
    restart: always
    environment:
      POSTGRES_DB: admission_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d admission_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: